# Generated by Django 5.0.6 on 2024-05-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_news', '0002_news_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
