# Generated by Django 5.0.6 on 2024-05-22 18:30

import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_file_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='files/', validators=[files.models.validate_file_size]),
        ),
    ]
