# Generated by Django 5.0.6 on 2024-05-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='forecast_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
