# Generated by Django 5.0.6 on 2024-05-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='max_temperature',
            field=models.CharField(max_length=50),
        ),
    ]
