# Generated by Django 5.0.6 on 2024-05-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('user_id', models.IntegerField(verbose_name='user_id')),
                ('additional', models.CharField(max_length=1100, null=True)),
            ],
        ),
    ]
