# Generated by Django 5.0.4 on 2024-05-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
