# Generated by Django 5.0.6 on 2024-05-21 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_contact_user_id_contact_address_contact_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='additional',
        ),
    ]
